version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_ai_tools
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_ai_tools
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    # הוסרה שורת ה-volume שמדרסת את node_modules

volumes:
  mysql_data:
